### ISSUE TITLE
Layout shift when changing loaders

### ISSUE THREAD

**Issue by Anuragtech02** [ashutosh1919/react-awesome-loaders#11]
#### Here is what I meant
![layout-shift](https://user-images.githubusercontent.com/55744578/108590474-cbb0af80-7389-11eb-969c-ccc6cf79642e.gif)

**Comment by ashutosh1919** [comment]
@Anuragtech02 , every loader has different entire page. Layout is not same. If you see the documentation website code, then there is a different mdx file corresponding to each loader.

Hence, closing this issue. Feel free to open it again if you think something is still erroneous.
