### ISSUE TITLE
Node sass issue preventing installation

### ISSUE THREAD

**Issue by TamjidTayeb** [ashutosh1919/react-awesome-loaders#12]
Hi,

I'm trying to install react-awesome-loaders for my react app but when i do i get this error:

npm ERR! Failed at the node-sass@4.14.1 postinstall

Any idea what the issue is?

I have already tried to remove pack-lock.json, node_modules and clear npm cache and reinstalling npm packages but I still get the same error.

My node version: 15.6.0
My node-sass version: 6.0.1

**Comment by ashutosh1919** [comment]
Hi, you can downgrade your node-sass version to match with react-awesome-loaders

**Comment by TamjidTayeb** [comment]
I tried that it did not resolve the issue, I had to downgrade my node verison to resolve the issue

**Comment by yohanelly95** [comment]
> I tried that it did not resolve the issue, I had to downgrade my node verison to resolve the issue

What version of node worked for you?

**Comment by ashutosh1919** [comment]
12.18.3
