### ISSUE TITLE
wifiloader has some console.log statements in it

### ISSUE THREAD

**Issue by onion2k** [ashutosh1919/react-awesome-loaders#2]
wifiloader.js has some console.log statements on lines 214-216. These should probably be removed in production builds.

**Comment by ashutosh1919** [comment]
@onion2k , are you interested in raising pull request?

**Comment by satyampandeygit** [comment]
@ashutosh1919 I can make PR regarding this

**Comment by ashutosh1919** [comment]
@satyampandeygit , go ahead and create a PR. I will be happy to review.

**Comment by ashutosh1919** [comment]
@onion2k , closing this as it is solved in #7 .
