### ISSUE TITLE
npm install is not working

### ISSUE THREAD

**Issue by nicolaesposito** [ashutosh1919/react-awesome-loaders#21]
base ❯ npm install react-awesome-loaders
npm WARN deprecated @babel/preset-es2015@7.0.0-beta.53: 👋 We've deprecated any official yearly presets in 6.x in favor or babel-preset-env. For 7.x it would be @babel/preset-env.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated rollup-plugin-terser@5.3.1: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh /var/folders/ls/v9q_x9m97pq66zyhkdwdh5w40000gn/T/postinstall-6579665a.sh
npm ERR! Building: /usr/local/bin/node /Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.17.1 | darwin | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /Users/nicolaesposito/opt/anaconda3/bin/python
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Command failed: /Users/nicolaesposito/opt/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:400:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Darwin 22.2.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/nicolaesposito/Documents/App/GIT/app.frontend.corintis/node_modules/react-awesome-loaders/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.17.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nicolaesposito/.npm/_logs/2022-12-20T17_16_44_444Z-debug-0.log

**Comment by bmspr1502** [comment]
Same error with me was there any fix available?

**Comment by ashutosh1919** [comment]
@bmspr1502 @nicolaesposito please update the node version to v16. I think your node version is deprecated
