### ISSUE TITLE
Cannot install due to dependency conflicts

### ISSUE THREAD

**Issue by TechWithTy** [ashutosh1919/react-awesome-loaders#22]
npm ERR! make: *** [binding.target.mk:133: Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/workspace/CyberOniLLC-/node_modules/react-awesome-loaders/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 5.15.0-47-generic
npm ERR! gyp ERR! command "/home/gitpod/.nvm/versions/node/v16.19.0/bin/node" "/workspace/CyberOniLLC-/node_modules/react-awesome-loaders/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /workspace/CyberOniLLC-/node_modules/react-awesome-loaders/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.19.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2023-03-20T16_31_49_152Z-debug-0.log

**Comment by atumas-bananamilk** [comment]
Same here.

**Comment by pbarker** [comment]
Same same

**Comment by renegadec** [comment]
anyone with a workaround the conflicts?

**Comment by Wamy-Dev** [comment]
nope, I think we just have to wait for an update

**Comment by bataevvlad** [comment]
any updates??

**Comment by krushil1** [comment]
same here. errors when installing the dependency

**Comment by Suhail-007** [comment]
facing the same issue

**Comment by ashutosh1919** [comment]
Did you try updating nodejs and npm to latest version?

**Comment by Suhail-007** [comment]
> Did you try updating nodejs and npm to latest version?

Using the latest version nothing changed

**Comment by ckcherry23** [comment]
Same here

**Comment by ashutosh1919** [comment]
@Suhail-007 we use node 12. Please upgrade or downgrade your version if you have different version
<img width="183" alt="Screenshot 2023-10-21 at 9 09 12 PM" src="https://github.com/ashutosh1919/react-awesome-loaders/assets/20843596/57f72121-cc5a-4501-9f47-77ccb0d6c97b">

**Comment by jannikstdl** [comment]
> @Suhail-007 we use node 12. Please upgrade or downgrade your version if you have different version <img alt="Screenshot 2023-10-21 at 9 09 12 PM" width="183" src="https://user-images.githubusercontent.com/20843596/277144874-57f72121-cc5a-4501-9f47-77ccb0d6c97b.png">

Why do you not update to the latest node version. I mean we have v18 nowerdays.

**Comment by Suhail-007** [comment]
> @Suhail-007 we use node 12. Please upgrade or downgrade your version if you have different version <img alt="Screenshot 2023-10-21 at 9 09 12 PM" width="183" src="https://user-images.githubusercontent.com/20843596/277144874-57f72121-cc5a-4501-9f47-77ccb0d6c97b.png">

It will break other things

**Comment by ashutosh1919** [comment]
@Suhail-007 @jnkstr Some of the packages are implemented keeping node v12 in mind. We need to have a look at it to see if we can upgrade. There may be some fixes to be done.

In the meantime, you can use nvm to use specific node version for particular project. It won't affect other projects on your computer

**Comment by Suhail-007** [comment]
> @Suhail-007 @jnkstr Some of the packages are implemented keeping node v12 in mind. We need to have a look at it to see if we can upgrade. There may be some fixes to be done.
> 
> In the meantime, you can use nvm to use specific node version for particular project. It won't affect other projects on your computer

Okay, thank you very much

**Comment by RobertMurfin** [comment]
> @Suhail-007 @jnkstr Some of the packages are implemented keeping node v12 in mind. We need to have a look at it to see if we can upgrade. There may be some fixes to be done.
> 
> In the meantime, you can use nvm to use specific node version for particular project. It won't affect other projects on your computer

I don't think anyone is still using v12 for new projects. Very unfortunate, your loaders are sick but 90% of the people will not be able to use this. I mean I use NextJS and it requires a minimum node version of 18.17.0, so it's impossible.

**Comment by ashutosh1919** [comment]
@RobertMurfin You are right and I am aware of it. I published this project several years ago and maintained it for 2 years. For now, I couldn't get time to fix problems and upgrade stuff. I am sorry for that. I will try in future. Meanwhile if someone is interested in fixing stuff, please feel free to raise PR.

**Comment by Suhail-007** [comment]
> @RobertMurfin You are right and I am aware of it. I published this project several years ago and maintained it for 2 years. For now, I couldn't get time to fix problems and upgrade stuff. I am sorry for that. I will try in future. Meanwhile if someone is interested in fixing stuff, please feel free to raise PR.

I will try in my free time.

**Comment by kjxcodez** [comment]
@ashutosh1919 I'm working on updates and trying to fix the issue.

**Comment by ckcherry23** [comment]
@CuriousCoder00 You can see the discussion on PR #24 and consider continuing on the same branch if it helps.

**Comment by tahdiislam** [comment]
Same here

**Comment by Jumagova** [comment]
I used `npm i react-awesome-loaders  --ignore-scripts && npm rebuild --verbose sharp` and works on node v22.4.0

**Comment by divyashah0510** [comment]
Thanks @Jumagova the command really helped!!
